### ISSUE TITLE
Allow user to specify Rust project directory

### ISSUE THREAD

**Issue by Megadash452** [andrefigas/RustJNI#1]
Hello, I found this repo through the [reddit post](https://www.reddit.com/r/rust/comments/1fs798t/rust_for_android/) and I think this is a great idea.

However i'm having some issues. First, my rust project is not inside the android project directory
```
└── MyProject/
    ├── rust/
    │   ├── Cargo.toml
    │   └── ...
    └── android/
        ├── app/
        ├── gradle/
        └── ...
```
But this plugin has the rust project path hard-coded to be inside the android project directory. So it would be nice to allow the user to specify the project path by having an option like `path = "../rust/"`.

The second issue is that the plugin expects to have `ndk.dir` in the `local.properties` file, but this file is auto-generated and is not commited to git, so this would have to be done every time a project is cloned. Instead, this option should be in `build.gradle`, or have the plugin automatically find this directory based on the `sdk.dir` or and environment variable like `ANDROID_SDK_HOME` or  `ANDROID_NDK_HOME`.

I can get started with implementing these changes, though I have no experience with making gradle plugins like this one.

**Comment by andrefigas** [comment]
Hey @Megadash452 , I really appreciated your contribution here.

Regarding allowing them to use a different directory, you are completely right. That is a use case I hadn’t thought about before. Thanks for pointing that out. I will review your PR soon. Thanks for that as well.

As for specifying the NDK version in the local properties, you're right again, but I’ve committed a solution for that. Basically, the local.properties (which is not committed) defines the path, but the NDK version has been moved to a plugin property.

https://github.com/andrefigas/RustJNI/commit/5b165aa3618b97aec200460023ec5cfdf52b4395

**Comment by Megadash452** [comment]
> As for specifying the NDK version in the local properties, you're right again, but I’ve committed a solution for that. Basically, the local.properties (which is not committed) defines the path, but the NDK version has been moved to a plugin property.

I did notice that when I was writing changes, but I also made it so that the NDK version doesn't have to be specified since it can just detect the latest version of NDK.

**Comment by andrefigas** [comment]
I guess if we assume the latest as a default, we could be creating that sad scenario: "It compiles on my machine"
