### ISSUE TITLE
Plugin fails to recognize Cargo commands in new project setup

### ISSUE THREAD

**Issue by andrefigas** [andrefigas/RustJNI#15]
When setting up a new project that uses the plugin, Gradle tasks fail to recognize and execute cargo commands, even though Cargo is properly installed and accessible in the terminal.

Issue Details
Running cargo --version in the Android Studio terminal returns the expected output, indicating that Cargo is installed and available in the system PATH.
However, when attempting to run a Gradle task that invokes cargo (e.g., cargo --version), it fails with the error: A problem occurred starting process 'command 'cargo''.

**Comment by Megadash452** [comment]
What causes this issue to occur? I tried it with the most recent commit in main and the plugin was still able to run `cargo new` without having to manually copy PATH to the exec method.

**Comment by andrefigas** [comment]
Bro, honestly, I don't know if this is a new or old issue. But, even though our samples keep working, I could not use our plugin in a new project.
I can add one more curious and funny fact: that changes were able to make my project work. After that, I removed that change, and it kept working. Maybe those values are cached anyway

**Comment by Megadash452** [comment]
I think that the gradle system is just not nice for developers of gradle plugins because I also ran into problems that vanished for no reason
